### ISSUE TITLE
Module 'lib' has no exported member 'movieFromBytes'

### ISSUE THREAD

**Issue by lOlbas** [open-flash/swf-parser#132]
When I run `npm run prestart` command I get the following error:

```
src\main\main.ts(5,10): error TS2305: Module '"../../../../../../../Documents/GitHub/swf/swf-parser/ts/src/lib"' has no exported member 'movieFromBytes'.
src\main\main.ts(23,5): error TS7027: Unreachable code detected.
```

which kind of makes sense because this name is only [used once in the same file](https://github.com/open-flash/swf-parser/search?q=movieFromBytes&unscoped_q=movieFromBytes), and is not declared anywhere

**Comment by demurgos** [comment]
Thank you for raising this issue. The function renamed to simply `parseSwf`. The README was updated but not the code example.

https://github.com/open-flash/swf-parser/tree/master/ts#usage

This project is primarily intended to be used as a library (not as its own CLI tool). I'm thinking of simply removing the example code in the `src/main` directory (or building it in CI).

If you want to use the parser from the terminal, I recommend using [the `parse` command from the `ofl` CLI program](https://github.com/open-flash/ofl#parse):
```
cargo install --git https://github.com/open-flash/ofl
ofl parse movie.swf
```

**Comment by lOlbas** [comment]
@demurgos thanks for the response! Changing the `movieFromBytes` to `parseSwf`, [unreachable code](https://github.com/open-flash/swf-parser/blob/e9cb33d1bd31ff69ab6908ab37402e46b32de59c/ts/src/main/main.ts#L23) and adding explicit import of TextEncoder/TextDecoder in `@open-flash/stream/readable.js` and `@open-flash/stream/writeable.js` (my NodeJS v10.15.0 was complaining of those being not defined) I successfully used this lib as CLI tool 🙂 Aaand I figured out there is an issue with frame rate reading: the value is read as little-endian while it should be big-endian. `0x0018` should be 24 FPS, got as 6144

**Comment by demurgos** [comment]
The framerate is returned as a FixedPoint number, what you see is the fractional count (epsilons). The framerate is expressed in 1/256 Herz. You can call `.valueOf()` (or use any mathematical operator) on `header.frameRate` to get the value in Herz (24 frames per second).
Serialization to JSON currently emits the inner epsilons instead of the value to avoid floating point numbers (because of compat issues between how they are serialized in various other languages). I agree that it would be easier: I'll look into it.

**Comment by demurgos** [comment]
Closing this issue as the README was update. Fixed point number serialization is tracked in open-flash/swf-types#93
