### ISSUE TITLE
Rust version doesn't build due to missing `ordered_float` dependency.

### ISSUE THREAD

**Issue by eddyb** [open-flash/swf-parser#3]
A change to `Cargo.toml` was made in https://github.com/open-flash/swf-parser/commit/5facdb84132ec4967d8b150c31dddffec9cf7cf4#diff-7ce0d359c33491fc5e6808df83bc7e2d that is not reflected in changes to the source or `Cargo.lock`.
Looks like `cargo build` or `cargo test` haven't been ran since?

It's also possible the `[replace]` was uncommented and the `swf-tree` version is older, but that wouldn't explain the removal of `ordered_float` without the code being updated.

**Comment by demurgos** [comment]
Fixed by the recent updates (`ordered_float` is no longer used).
