### ISSUE TITLE
Latest version published on crates.io is 0.0.8 but Cargo.toml says 0.0.2.

### ISSUE THREAD

**Issue by eddyb** [open-flash/swf-parser#4]
Could this be related to #3?

**Comment by demurgos** [comment]
Hi,
Thanks for raising the issue. I was working on my own and wasn't expecting/looking into the issues on the Github repo. Now that I am aware that some people are looking into this, I'll be more careful with my updates and make sure to publish the updates to `crates.io`. 

I am now happy with the AST and the parsers/emitters for SWF tags and AVM1 are getting stable. I am now adding CI to these repos, ensuring that the Rust and TS versions are in sync and adding more tests.
I am now closing on this dev cycle and integrating the new renderer and AVM support to [domu-player](https://github.com/open-flash/domu-player/). I hope to finish it soon. I'll then start to stabilize all the crates/packages written so far so they can be reused. I'll leave this issue open until it is done, I'll notify you too.

**Comment by demurgos** [comment]
Closing this issue: the AST and parser are more stable now, and the Rust version is up-to-date.
